language: go

dist: xenial

go:
  - 1.13.x

env:
  global:
    - FASTDL=http://downloads.mongodb.org
  matrix:
    - VERSION=3.6.14
    - VERSION=4.0.12
    - VERSION=4.2.0

before_script: 
  - wget $FASTDL/linux/mongodb-linux-x86_64-ubuntu1604-$VERSION.tgz
  - tar xzvf mongodb-linux-x86_64-ubuntu1604-$VERSION.tgz
  - export PATH=$PWD/mongodb-linux-x86_64-ubuntu1604-$VERSION/bin:$PATH
  - mkdir $PWD/db
  - mongod --dbpath $PWD/db > /dev/null &

  - go build 
  - go get -u golang.org/x/lint/golint
  - golint ./... 
  - go vet ./...

script:
  - ./test.sh
  - ./mgodatagen -f datagen/testdata/big.json
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false

git:
  depth: 3
