language: go

go:
  - 1.8.3
  - 1.9
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

services: 
  - mongodb

before_script: 
  - go build 
script:
  - go test -v ./...
  - go test -v ./... -bench=. -benchmem
  - ./mgodatagen -f samples/config.json
  
notifications: 
  email: false

git:
  depth: 3
