language: go

go:
  - 1.8.x
  - 1.9.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

services: 
  - mongodb

before_script: 
  - go build 
  - go get github.com/golang/lint/golint
  - golint ./... 
  - go vet ./...

script:
  - go test -v ./... 
  - ./mgodatagen -f samples/config.json
  - ./mgodatagen -f samples/agg.json

notifications: 
  email: false

git:
  depth: 3
