language: go
sudo: required
go:
  - 1.8.3
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
services: 
  - mongodb
before_script: 
  - go build 
script:
  - go test
  - go test -bench=. -benchmem
  - time ./mgodatagen -f samples/config.json
  
notifications: 
  email: false

git:
  depth: 3
