language: go

os: 
  - linux
  - osx

dist: xenial

go:
  - 1.12.x

env:
  global:
    - FASTDL=http://downloads.mongodb.org
  matrix:
    - ARCH=x86_64 DIST=-ubuntu1604 VERSION=3.4.19
    - ARCH=x86_64 DIST=-ubuntu1604 VERSION=3.6.12
    - ARCH=x86_64 DIST=-ubuntu1604 VERSION=4.0.9

before_script: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then DIST=""; SSL="-ssl" ; fi
  - wget $FASTDL/$TRAVIS_OS_NAME/mongodb-$TRAVIS_OS_NAME$SSL-$ARCH$DIST-$VERSION.tgz
  - tar xzvf mongodb-$TRAVIS_OS_NAME$SSL-$ARCH$DIST-$VERSION.tgz
  - export PATH=$PWD/mongodb-$TRAVIS_OS_NAME-$ARCH$DIST-$VERSION/bin:$PATH
  - mkdir $PWD/db
  - mongod --dbpath $PWD/db > /dev/null &

  - go build 
  - go get -u golang.org/x/lint/golint
  - golint ./... 
  - go vet ./...

script:
  - ./test.sh
  - ./mgodatagen -f datagen/testdata/big.json
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications: 
  email: false

git:
  depth: 3
