language: go
sudo: required

cache:
  directories:
    - $HOME/Library/Caches/Homebrew

go:
  - 1.8.3
  - 1.9

os:
  - linux
  - osx

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

services: 
  - mongodb

before_script: 
  - go build 
  - scripts/setup_osx.sh 
script:
  - go test -v ./...
  - go test -bench=. -benchmem
  - ./mgodatagen -f samples/config.json
  
notifications: 
  email: false

git:
  depth: 3
